/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Rock {

public class Rock_Shared {
  public static readonly int _UNICODE = Rock_SharedPINVOKE._UNICODE_get();
  public static readonly int _WIN32 = Rock_SharedPINVOKE._WIN32_get();
}

}
