/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Rock {

class Rock_SharedPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="SWIGRegisterExceptionCallbacks_Rock_Shared")]
    public static extern void SWIGRegisterExceptionCallbacks_Rock_Shared(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_Rock_Shared")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_Rock_Shared(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_Rock_Shared(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_Rock_Shared(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(Rock_SharedPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(Rock_SharedPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="SWIGRegisterStringCallback_Rock_Shared")]
    public static extern void SWIGRegisterStringCallback_Rock_Shared(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_Rock_Shared(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static Rock_SharedPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp__UNICODE_get")]
  public static extern int _UNICODE_get();

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp__SWIG_get")]
  public static extern int _SWIG_get();

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp__WINDOWS_get")]
  public static extern int _WINDOWS_get();

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp__WIN32_get")]
  public static extern int _WIN32_get();

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__11_set")]
  public static extern void Matrix4x4__11_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__11_get")]
  public static extern float Matrix4x4__11_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__12_set")]
  public static extern void Matrix4x4__12_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__12_get")]
  public static extern float Matrix4x4__12_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__13_set")]
  public static extern void Matrix4x4__13_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__13_get")]
  public static extern float Matrix4x4__13_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__14_set")]
  public static extern void Matrix4x4__14_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__14_get")]
  public static extern float Matrix4x4__14_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__21_set")]
  public static extern void Matrix4x4__21_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__21_get")]
  public static extern float Matrix4x4__21_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__22_set")]
  public static extern void Matrix4x4__22_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__22_get")]
  public static extern float Matrix4x4__22_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__23_set")]
  public static extern void Matrix4x4__23_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__23_get")]
  public static extern float Matrix4x4__23_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__24_set")]
  public static extern void Matrix4x4__24_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__24_get")]
  public static extern float Matrix4x4__24_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__31_set")]
  public static extern void Matrix4x4__31_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__31_get")]
  public static extern float Matrix4x4__31_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__32_set")]
  public static extern void Matrix4x4__32_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__32_get")]
  public static extern float Matrix4x4__32_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__33_set")]
  public static extern void Matrix4x4__33_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__33_get")]
  public static extern float Matrix4x4__33_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__34_set")]
  public static extern void Matrix4x4__34_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__34_get")]
  public static extern float Matrix4x4__34_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__41_set")]
  public static extern void Matrix4x4__41_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__41_get")]
  public static extern float Matrix4x4__41_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__42_set")]
  public static extern void Matrix4x4__42_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__42_get")]
  public static extern float Matrix4x4__42_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__43_set")]
  public static extern void Matrix4x4__43_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__43_get")]
  public static extern float Matrix4x4__43_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__44_set")]
  public static extern void Matrix4x4__44_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4__44_get")]
  public static extern float Matrix4x4__44_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_rc_set")]
  public static extern void Matrix4x4_rc_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_rc_get")]
  public static extern global::System.IntPtr Matrix4x4_rc_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_v_set")]
  public static extern void Matrix4x4_v_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_v_get")]
  public static extern global::System.IntPtr Matrix4x4_v_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_new_Matrix4x4__SWIG_0")]
  public static extern global::System.IntPtr new_Matrix4x4__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_new_Matrix4x4__SWIG_1")]
  public static extern global::System.IntPtr new_Matrix4x4__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_delete_Matrix4x4")]
  public static extern void delete_Matrix4x4(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetRow__SWIG_0")]
  public static extern void Matrix4x4_SetRow__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetRow__SWIG_1")]
  public static extern void Matrix4x4_SetRow__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3, float jarg4, float jarg5, float jarg6);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetColumn__SWIG_0")]
  public static extern void Matrix4x4_SetColumn__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetColumn__SWIG_1")]
  public static extern void Matrix4x4_SetColumn__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3, float jarg4, float jarg5, float jarg6);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetAxisX__SWIG_0")]
  public static extern void Matrix4x4_SetAxisX__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetAxisX__SWIG_1")]
  public static extern void Matrix4x4_SetAxisX__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetAxisY__SWIG_0")]
  public static extern void Matrix4x4_SetAxisY__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetAxisY__SWIG_1")]
  public static extern void Matrix4x4_SetAxisY__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetAxisZ__SWIG_0")]
  public static extern void Matrix4x4_SetAxisZ__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetAxisZ__SWIG_1")]
  public static extern void Matrix4x4_SetAxisZ__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetPosition__SWIG_0")]
  public static extern void Matrix4x4_SetPosition__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetPosition__SWIG_1")]
  public static extern void Matrix4x4_SetPosition__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_SetCell")]
  public static extern void Matrix4x4_SetCell(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetRow__SWIG_0")]
  public static extern global::System.IntPtr Matrix4x4_GetRow__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetColumn__SWIG_0")]
  public static extern global::System.IntPtr Matrix4x4_GetColumn__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetAxisX__SWIG_0")]
  public static extern global::System.IntPtr Matrix4x4_GetAxisX__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetAxisY__SWIG_0")]
  public static extern global::System.IntPtr Matrix4x4_GetAxisY__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetAxisZ__SWIG_0")]
  public static extern global::System.IntPtr Matrix4x4_GetAxisZ__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetPosition__SWIG_0")]
  public static extern global::System.IntPtr Matrix4x4_GetPosition__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetCell__SWIG_0")]
  public static extern float Matrix4x4_GetCell__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetRow__SWIG_1")]
  public static extern void Matrix4x4_GetRow__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetColumn__SWIG_1")]
  public static extern void Matrix4x4_GetColumn__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetAxisX__SWIG_1")]
  public static extern void Matrix4x4_GetAxisX__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetAxisY__SWIG_1")]
  public static extern void Matrix4x4_GetAxisY__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetAxisZ__SWIG_1")]
  public static extern void Matrix4x4_GetAxisZ__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetPosition__SWIG_1")]
  public static extern void Matrix4x4_GetPosition__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_GetCell__SWIG_1")]
  public static extern void Matrix4x4_GetCell__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_Identity")]
  public static extern void Matrix4x4_Identity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_Inverse")]
  public static extern void Matrix4x4_Inverse(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_Transpose")]
  public static extern void Matrix4x4_Transpose(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_Inversed__SWIG_0")]
  public static extern global::System.IntPtr Matrix4x4_Inversed__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_Transposed__SWIG_0")]
  public static extern global::System.IntPtr Matrix4x4_Transposed__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_Inversed__SWIG_1")]
  public static extern void Matrix4x4_Inversed__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_Transposed__SWIG_1")]
  public static extern void Matrix4x4_Transposed__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreatePerspectiveLH")]
  public static extern global::System.IntPtr Matrix4x4_CreatePerspectiveLH(float jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreatePerspectiveRH")]
  public static extern global::System.IntPtr Matrix4x4_CreatePerspectiveRH(float jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreateIdentity")]
  public static extern global::System.IntPtr Matrix4x4_CreateIdentity();

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreateViewLH")]
  public static extern global::System.IntPtr Matrix4x4_CreateViewLH(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreateViewRH")]
  public static extern global::System.IntPtr Matrix4x4_CreateViewRH(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreateScale")]
  public static extern global::System.IntPtr Matrix4x4_CreateScale(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreateTranslate")]
  public static extern global::System.IntPtr Matrix4x4_CreateTranslate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreateRotateX")]
  public static extern global::System.IntPtr Matrix4x4_CreateRotateX(float jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreateRotateY")]
  public static extern global::System.IntPtr Matrix4x4_CreateRotateY(float jarg1);

  [global::System.Runtime.InteropServices.DllImport("Rock_Shared", EntryPoint="CSharp_Matrix4x4_CreateRotateZ")]
  public static extern global::System.IntPtr Matrix4x4_CreateRotateZ(float jarg1);
}

}
