/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Rock {
  public static readonly int _UNICODE = RockPINVOKE._UNICODE_get();
  public static readonly int _WIN32 = RockPINVOKE._WIN32_get();
}
