/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Vector3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vector3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vector3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vector3() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RockPINVOKE.delete_Vector3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_RFLOAT x {
    set {
      RockPINVOKE.Vector3_x_set(swigCPtr, SWIGTYPE_p_RFLOAT.getCPtr(value));
      if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_RFLOAT ret = new SWIGTYPE_p_RFLOAT(RockPINVOKE.Vector3_x_get(swigCPtr), true);
      if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_RFLOAT y {
    set {
      RockPINVOKE.Vector3_y_set(swigCPtr, SWIGTYPE_p_RFLOAT.getCPtr(value));
      if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_RFLOAT ret = new SWIGTYPE_p_RFLOAT(RockPINVOKE.Vector3_y_get(swigCPtr), true);
      if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_RFLOAT z {
    set {
      RockPINVOKE.Vector3_z_set(swigCPtr, SWIGTYPE_p_RFLOAT.getCPtr(value));
      if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_RFLOAT ret = new SWIGTYPE_p_RFLOAT(RockPINVOKE.Vector3_z_get(swigCPtr), true);
      if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Vector3() : this(RockPINVOKE.new_Vector3__SWIG_0(), true) {
  }

  public Vector3(SWIGTYPE_p_RFLOAT v) : this(RockPINVOKE.new_Vector3__SWIG_1(SWIGTYPE_p_RFLOAT.getCPtr(v)), true) {
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3(SWIGTYPE_p_RFLOAT x, SWIGTYPE_p_RFLOAT y, SWIGTYPE_p_RFLOAT z) : this(RockPINVOKE.new_Vector3__SWIG_2(SWIGTYPE_p_RFLOAT.getCPtr(x), SWIGTYPE_p_RFLOAT.getCPtr(y), SWIGTYPE_p_RFLOAT.getCPtr(z)), true) {
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3(Vector3 vCopy) : this(RockPINVOKE.new_Vector3__SWIG_3(Vector3.getCPtr(vCopy)), true) {
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Normalize() {
    RockPINVOKE.Vector3_Normalize(swigCPtr);
  }

  public Vector3 Normalized() {
    Vector3 ret = new Vector3(RockPINVOKE.Vector3_Normalized__SWIG_0(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_RFLOAT Length() {
    SWIGTYPE_p_RFLOAT ret = new SWIGTYPE_p_RFLOAT(RockPINVOKE.Vector3_Length__SWIG_0(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_RFLOAT LengthSq() {
    SWIGTYPE_p_RFLOAT ret = new SWIGTYPE_p_RFLOAT(RockPINVOKE.Vector3_LengthSq__SWIG_0(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_RFLOAT Distance(Vector3 vVector) {
    SWIGTYPE_p_RFLOAT ret = new SWIGTYPE_p_RFLOAT(RockPINVOKE.Vector3_Distance__SWIG_0(swigCPtr, Vector3.getCPtr(vVector)), true);
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_RFLOAT Dot(Vector3 vVector) {
    SWIGTYPE_p_RFLOAT ret = new SWIGTYPE_p_RFLOAT(RockPINVOKE.Vector3_Dot__SWIG_0(swigCPtr, Vector3.getCPtr(vVector)), true);
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3 CrossLH(Vector3 vVector) {
    Vector3 ret = new Vector3(RockPINVOKE.Vector3_CrossLH__SWIG_0(swigCPtr, Vector3.getCPtr(vVector)), true);
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3 CrossRH(Vector3 vVector) {
    Vector3 ret = new Vector3(RockPINVOKE.Vector3_CrossRH__SWIG_0(swigCPtr, Vector3.getCPtr(vVector)), true);
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Normalized(Vector3 o_vNormalized) {
    RockPINVOKE.Vector3_Normalized__SWIG_1(swigCPtr, Vector3.getCPtr(o_vNormalized));
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Length(SWIGTYPE_p_RFLOAT o_nLength) {
    RockPINVOKE.Vector3_Length__SWIG_1(swigCPtr, SWIGTYPE_p_RFLOAT.getCPtr(o_nLength));
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

  public void LengthSq(SWIGTYPE_p_RFLOAT o_nLength) {
    RockPINVOKE.Vector3_LengthSq__SWIG_1(swigCPtr, SWIGTYPE_p_RFLOAT.getCPtr(o_nLength));
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Distance(Vector3 vVector, SWIGTYPE_p_RFLOAT o_nDistance) {
    RockPINVOKE.Vector3_Distance__SWIG_1(swigCPtr, Vector3.getCPtr(vVector), SWIGTYPE_p_RFLOAT.getCPtr(o_nDistance));
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Dot(Vector3 vVector, SWIGTYPE_p_RFLOAT o_nDot) {
    RockPINVOKE.Vector3_Dot__SWIG_1(swigCPtr, Vector3.getCPtr(vVector), SWIGTYPE_p_RFLOAT.getCPtr(o_nDot));
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

  public void CrossLH(Vector3 vVector, Vector3 o_vCross) {
    RockPINVOKE.Vector3_CrossLH__SWIG_1(swigCPtr, Vector3.getCPtr(vVector), Vector3.getCPtr(o_vCross));
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

  public void CrossRH(Vector3 vVector, Vector3 o_vCross) {
    RockPINVOKE.Vector3_CrossRH__SWIG_1(swigCPtr, Vector3.getCPtr(vVector), Vector3.getCPtr(o_vCross));
    if (RockPINVOKE.SWIGPendingException.Pending) throw RockPINVOKE.SWIGPendingException.Retrieve();
  }

}
