/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Diamond {

public class Diamond_Shared {
  public static readonly int _H_DIAMOND_SCENE = Diamond_SharedPINVOKE._H_DIAMOND_SCENE_get();
  public static readonly int _H_DIAMOND_SCENEVIEW = Diamond_SharedPINVOKE._H_DIAMOND_SCENEVIEW_get();
}

}
