/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Diamond {

public class SceneView : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SceneView(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SceneView obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SceneView() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Diamond_SharedPINVOKE.delete_SceneView(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void SetSize(uint nWidth, uint nHeight) {
    Diamond_SharedPINVOKE.SceneView_SetSize(swigCPtr, nWidth, nHeight);
  }

  public void SetFullscreen(bool bFullscreen) {
    Diamond_SharedPINVOKE.SceneView_SetFullscreen(swigCPtr, bFullscreen);
  }

  public uint GetWidth() {
    uint ret = Diamond_SharedPINVOKE.SceneView_GetWidth(swigCPtr);
    return ret;
  }

  public uint GetHeight() {
    uint ret = Diamond_SharedPINVOKE.SceneView_GetHeight(swigCPtr);
    return ret;
  }

  public bool GetFullscreen() {
    bool ret = Diamond_SharedPINVOKE.SceneView_GetFullscreen(swigCPtr);
    return ret;
  }

}

}
